zipcodes:
  - zip: '02110'
    cron: '0 * * * *'  # every hour
  - zip: '33871'
    cron: '0 * * * *'
  - zip: '96801'
    cron: '0 * * * *'
  - zip: '99524'
    cron: '0 * * * *'
  - zip: '82941'
    cron: '0 * * * *'
  - zip: '84321'
    cron: '0 * * * *'
  - zip: '07039'
    cron: '0 * * * *'
  - zip: '39530'
    cron: '0 * * * *'
  - zip: '33710'
    cron: '0 * * * *'
  - zip: '01844'
    cron: '0 * * * *'
  