default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: weather_development
  username: weather     # normally would use ENV['DBUSER']
  password: weather     # normally would use ENV['DBPASS']
  host: localhost

test:
  <<: *default
  database: weather_test
  username: weather
  password: weather
  host: localhost

production:
  <<: *default
  database: weather_production
  username: weather
  password: weather
  host: localhost
